name = "MultibodyDynamicsLite"
uuid = "6e976550-d483-49cc-8a64-303d39d4aebc"
authors = ["Grzegorz Orzechowski <2590699+gorzech@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.9.13"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
