name = "MultibodyDynamicsLite"
uuid = "6e976550-d483-49cc-8a64-303d39d4aebc"
authors = ["Grzegorz Orzechowski <2590699+gorzech@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
ForwardDiff = "1.0.1"
LinearAlgebra = "1.11.0"
Revise = "3.7.6"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
